logger:
  enable: true
  level: debug
  format: compact

server:
  port: 5150
  host: 0.0.0.0
  middlewares:
    cors:
      enable: true
      allow_origins: [any]
      allow_headers:
        - "*"
      allow_methods:
        - "*"

database:
  min_connections: 1
  max_connections: 1
  connect_timeout: 30
  idle_timeout: 3600
  uri: "sqlite://db.sqlite?mode=rwc"
  enable_logging: false
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false
